/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DepartmentTeam: typeof import('./src/components/DepartmentTeam.vue')['default']
    HyperLink: typeof import('./src/components/HyperLink.vue')['default']
    IntroButton: typeof import('./src/components/IntroButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialButton: typeof import('./src/components/SocialButton.vue')['default']
    TeamCard: typeof import('./src/components/TeamCard.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheFooterLinks: typeof import('./src/components/TheFooterLinks.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheIntroButton: typeof import('./src/components/TheIntroButton.vue')['default']
    TheIntroFrame: typeof import('./src/components/TheIntroFrame.vue')['default']
    TheMenu: typeof import('./src/components/TheMenu.vue')['default']
    TheSideMenu: typeof import('./src/components/TheSideMenu.vue')['default']
  }
}
